CREATE TABLE Locations(
    load_date   TIMESTAMP default now(),
    update_date TIMESTAMP default now(),
    name        VARCHAR(1000),
    region      VARCHAR(MAX),
    country     VARCHAR(1000),
    latitude    NUMERIC(6,3),
    longitude   NUMERIC(6,3),
    tz_id       VARCHAR(1000),
    localdate   TIMESTAMP
)

CREATE TABLE ForecastDay(
    load_date               TIMESTAMP default now(),
    update_date             TIMESTAMP default now(),
    date                    TIMESTAMP,
    maxtemp_c               NUMERIC(5,2),
    maxtemp_f               NUMERIC(5,2),
    mintemp_c               NUMERIC(5,2),
    mintemp_f               NUMERIC(5,2),
    avgtemp_c               NUMERIC(5,2),
    avgtemp_f               NUMERIC(5,2),
    maxwind_mph             NUMERIC(5,2),
    maxwind_kph             NUMERIC(5,2),
    totalprecip_mm          NUMERIC(5,2),
    totalprecip_in          NUMERIC(5,2),
    totalsnow_cm            NUMERIC(5,2),
    avgvis_km               NUMERIC(5,2),
    avgvis_miles            NUMERIC(5,2),
    avghumidity             NUMERIC(5,2),
    daily_will_it_rain      NUMERIC(5,2),
    daily_chance_of_rain    NUMERIC(5,2),
    daily_will_it_snow      NUMERIC(5,2),
    daily_chance_of_snow    NUMERIC(5,2),
    condition_text          VARCHAR(1000),
    condition_icon          VARCHAR(1000),
    condition_code          INTEGER,
    uv                      NUMERIC(4,2),
    sunrise                 TIMESTAMP,
    sunset                  TIMESTAMP,
    moonrise                TIMESTAMP,
    moonset                 TIMESTAMP,
    moon_phase              VARCHAR(100),
    moon_illumination       INTEGER
)

CREATE TABLE HourForecast(
    load_date       TIMESTAMP default now(),
    update_date     TIMESTAMP default now(),
    time            TIMESTAMP,
    temp_c          NUMERIC(5,2),
    temp_f          NUMERIC(5,2),
    is_day          BOOLEAN,
    condition_text  VARCHAR(100),
    condition_icon  VARCHAR(100),
    condition_code  INTEGER,
    wind_mph        NUMERIC(6,2),
    wind_kph        NUMERIC(6,2),
    wind_degree     INTEGER,
    wind_dir        VARCHAR(10),
    pressure_mb     NUMERIC(6,2),
    pressure_in     NUMERIC(5,2),
    precip_mm       NUMERIC(10,2),
    precip_in       NUMERIC(10,2),
    snow_cm         NUMERIC(10,2),
    humidity        NUMERIC(5,2),
    cloud           NUMERIC(5,2),
    feelslike_c     NUMERIC(5,2),
    feelslike_f     NUMERIC(5,2),
    windchill_c     NUMERIC(5,2),
    windchill_f     NUMERIC(5,2),
    heatindex_c     NUMERIC(5,2),
    heatindex_f     NUMERIC(5,2),
    dewpoint_c      NUMERIC(5,2),
    dewpoint_f      NUMERIC(5,2),
    will_it_rain    BOOLEAN,
    chance_of_rain  NUMERIC(5,2),
    will_it_snow    BOOLEAN,
    chance_of_snow  NUMERIC(5,2),
    vis_km          NUMERIC(6,2),
    vis_miles       NUMERIC(6,2),
    gust_mph        NUMERIC(6,2),
    gust_kph        NUMERIC(6,2),
    uv              NUMERIC(5,2)
)