CREATE TABLE Locations(
    load_date   TIMESTAMP default now(),
    update_date TIMESTAMP default now(),
    name        VARCHAR(1000),
    region      VARCHAR(MAX),
    country     VARCHAR(1000),
    latitude    NUMERIC(6,3),
    longitude   NUMERIC(6,3),
    tz_id       VARCHAR(1000),
    localdate   TIMESTAMP
)

CREATE TABLE ForecastDay(
    load_date               TIMESTAMP default now(),
    update_date             TIMESTAMP default now(),
    date                    TIMESTAMP,
    maxtemp_c               NUMERIC(5,2),
    maxtemp_f               NUMERIC(5,2),
    mintemp_c               NUMERIC(5,2),
    mintemp_f               NUMERIC(5,2),
    avgtemp_c               NUMERIC(5,2),
    avgtemp_f               NUMERIC(5,2),
    maxwind_mph             NUMERIC(5,2),
    maxwind_kph             NUMERIC(5,2),
    totalprecip_mm          NUMERIC(5,2),
    totalprecip_in          NUMERIC(5,2),
    totalsnow_cm            NUMERIC(5,2),
    avgvis_km               NUMERIC(5,2),
    avgvis_miles            NUMERIC(5,2),
    avghumidity             NUMERIC(5,2),
    daily_will_it_rain      NUMERIC(5,2),
    daily_chance_of_rain    NUMERIC(5,2),
    daily_will_it_snow      NUMERIC(5,2),
    daily_chance_of_snow    NUMERIC(5,2),
    condition_text          VARCHAR(1000),
    condition_icon          VARCHAR(1000),
    condition_code          INTEGER,
    uv                      NUMERIC(4,2),
    sunrise                 TIMESTAMP,
    sunset                  TIMESTAMP,
    moonrise                TIMESTAMP,
    moonset                 TIMESTAMP,
    moon_phase              VARCHAR(100),
    moon_illumination       INTEGER
)

CREATE TABLE HourForecast(
    load_date       TIMESTAMP default now(),
    update_date     TIMESTAMP default now(),
    time            TIMESTAMP,
    temp_c          NUMERIC(5,2),
    temp_f          NUMERIC(5,2),
    is_day          BOOLEAN,
    condition_text  VARCHAR(100),
    condition_icon  VARCHAR(100),
    condition_code  INTEGER,
    wind_mph        NUMERIC(6,2),
    wind_kph        NUMERIC(6,2),
    wind_degree     INTEGER,
    wind_dir        VARCHAR(10),
    pressure_mb     NUMERIC(6,2),
    pressure_in     NUMERIC(5,2),
    precip_mm       NUMERIC(10,2),
    precip_in       NUMERIC(10,2),
    snow_cm         NUMERIC(10,2),
    humidity        NUMERIC(5,2),
    cloud           NUMERIC(5,2),
    feelslike_c     NUMERIC(5,2),
    feelslike_f     NUMERIC(5,2),
    windchill_c     NUMERIC(5,2),
    windchill_f     NUMERIC(5,2),
    heatindex_c     NUMERIC(5,2),
    heatindex_f     NUMERIC(5,2),
    dewpoint_c      NUMERIC(5,2),
    dewpoint_f      NUMERIC(5,2),
    will_it_rain    BOOLEAN,
    chance_of_rain  NUMERIC(5,2),
    will_it_snow    BOOLEAN,
    chance_of_snow  NUMERIC(5,2),
    vis_km          NUMERIC(6,2),
    vis_miles       NUMERIC(6,2),
    gust_mph        NUMERIC(6,2),
    gust_kph        NUMERIC(6,2),
    uv              NUMERIC(5,2)
)

/* - Segunda Entrega - */

CREATE TABLE forecast (
        name TEXT,
        region TEXT,
        country TEXT,
        latitude FLOAT(53),
        longitude FLOAT(53),
        tz_id TEXT,
        localdate TEXT,
        load_date_x TIMESTAMP WITHOUT TIME ZONE,
        update_date_x TIMESTAMP WITHOUT TIME ZONE,
        date_x TEXT,
        maxtemp_c FLOAT(53),
        maxtemp_f FLOAT(53),
        mintemp_c FLOAT(53),
        mintemp_f FLOAT(53),
        avgtemp_c FLOAT(53),
        avgtemp_f FLOAT(53),
        maxwind_mph FLOAT(53),
        maxwind_kph FLOAT(53),
        totalprecip_mm FLOAT(53),
        totalprecip_in FLOAT(53),
        totalsnow_cm FLOAT(53),
        avgvis_km FLOAT(53),
        avgvis_miles FLOAT(53),
        avghumidity BIGINT,
        daily_will_it_rain BIGINT,
        daily_chance_of_rain BIGINT,
        daily_will_it_snow BIGINT,
        daily_chance_of_snow BIGINT,
        condition_text_x TEXT,
        condition_icon_x TEXT,
        condition_code_x BIGINT,
        uv_x FLOAT(53),
        sunrise TEXT,
        sunset TEXT,
        moonrise TEXT,
        moonset TEXT,
        moon_phase TEXT,
        moon_illumination BIGINT,
        load_date_y TIMESTAMP WITHOUT TIME ZONE,
        update_date_y TIMESTAMP WITHOUT TIME ZONE,
        location_id TEXT,
        time TEXT,
        temp_c FLOAT(53),
        temp_f FLOAT(53),
        is_day BIGINT,
        wind_mph FLOAT(53),
        wind_kph FLOAT(53),
        wind_degree BIGINT,
        wind_dir TEXT,
        pressure_mb FLOAT(53),
        pressure_in FLOAT(53),
        precip_mm FLOAT(53),
        precip_in FLOAT(53),
        snow_cm FLOAT(53),
        humidity BIGINT,
        cloud BIGINT,
        feelslike_c FLOAT(53),
        feelslike_f FLOAT(53),
        windchill_c FLOAT(53),
        windchill_f FLOAT(53),
        heatindex_c FLOAT(53),
        heatindex_f FLOAT(53),
        dewpoint_c FLOAT(53),
        dewpoint_f FLOAT(53),
        will_it_rain BIGINT,
        chance_of_rain BIGINT,
        will_it_snow BIGINT,
        chance_of_snow BIGINT,
        vis_km FLOAT(53),
        vis_miles FLOAT(53),
        gust_mph FLOAT(53),
        gust_kph FLOAT(53),
        uv_y FLOAT(53),
        condition_text_y TEXT,
        condition_icon_y TEXT,
        condition_code_y BIGINT,
        date_y TEXT,
        load_date TIMESTAMP WITHOUT TIME ZONE,
        update_date TIMESTAMP WITHOUT TIME ZONE
)
